version: '3.8'
services:
  orio-telegram-adapter-local:
    # TODO: investigate how to start container without it
    privileged: true
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    env_file: ./bot.env
