FROM docker.io/library/golang:1.22.1-alpine3.19

WORKDIR /app

RUN go install github.com/Open-Remote-I-O/cert_gen_cli@v0.1.4

# Add you're CA authority certificate in order to allow mTLS communication
COPY ca.crt /etc/ssl/certs/orio-ca.crt
COPY ca.key /etc/ssl/private/orio-ca.key

RUN cert_gen_cli genCaParentCert --organization-name orio-local -o /etc/ssl/certs/ -n orio-server -c /etc/ssl/certs/orio-ca.crt -k /etc/ssl/private/orio-ca.key

RUN go install github.com/cosmtrek/air@v1.49.0

CMD ["air", "-c", ".air.toml"]
