version: '3.8'

# NOTE :Extension field used in order to 
# avoid volume name duplication
# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-orio-root:
  &orio-root
  type: bind
  source: ./
  target: /app

services:
  orio-telegram-adapter:
    # TODO: investigate how to start container without it when using podman as container engine
    privileged: true
    environment:
        DEVICE_CONTROL_PORT: ${DEVICE_CONTROL_PORT}
        LOCAL_DEVICE_CONTROL_PORT: ${LOCAL_DEVICE_CONTROL_PORT}
        BOT_API_KEY: ${BOT_API_KEY}
    ports:
      - "${DEVICE_CONTROL_PORT}:${LOCAL_DEVICE_CONTROL_PORT}/tcp"
    expose:
      - "${LOCAL_DEVICE_CONTROL_PORT}"
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - *orio-root
    network:
      - ip6net

  orio-mock-device:
    # TODO: investigate how to start container without it when using podman as container engine
    privileged: true
    restart: on-failure
    environment:
        LOCAL_DEVICE_CONTROL_PORT: ${LOCAL_DEVICE_CONTROL_PORT}
        SERVER_ADDR_NAME: ${SERVER_ADDR_NAME}
    build:
      dockerfile: mock/device/Dockerfile
      context: .
    volumes:
      - *orio-root
    links: 
      - orio-telegram-adapter
    network:
      - ip6net

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
