[CertificateMetadata]
OrganizationName = "test"
SubjectCommonName = "test"
DnsNames = ["localhost","orio-server","orio-telegram-adapter"]
IPAddresses = ["127.0.0.1"]

[EncryptionAlgorithm]
EncAlgorithm = "RSA" # RSA or EDCSA currently available 
EncBits = 2048 # 1024 - 4096 supported for rsa 224 256 384 521 values supported
